### ISSUE TITLE
"Packet 0/84 (yl) was larger that I expected"

### ISSUE THREAD

**Issue by LOCNetwork** [CatCoderr/ProtocolSidebar#12]
Hello,

While using this API in 1.19.4, with the correct ProtocolLib version (#618) I can not join my server because of an error related to packets. I am not getting any errors in the console, only in the Minecraft Client.
I will leave a screenshot of this error below: 

<img width="413" alt="Error" src="https://user-images.githubusercontent.com/77237451/227731925-be65dd01-2dbd-4bc4-867c-89fb361d9abb.png">

Thank you,
Joseda.

**Comment by LOCNetwork** [comment]
Another thing is that I tested and this does not happen in 1.19.2

**Comment by CatCoderr** [comment]
Should be fixed on 6.1.4-SNAPSHOT
