### ISSUE TITLE
[SUGGESTION] Add new type of lines which their visibility depends on something

### ISSUE THREAD

**Issue by LOCNetwork** [CatCoderr/ProtocolSidebar#30]
Hello,
It would be amazing if you could add a new type of line to the API. This new type will only be visible if a condition is met. For example, if you are in a team, a new line (which couldn't be seen before) in the scoreboard would appear telling you your team, and when you leave the team, that line will disappear again making the scoreboard smaller. 
I don't mean a line that would just be an empty space and then when the condition is met, some text appears, but rather a line that does not exist visually in the scoreboard, and when it appears, the scoreboard would be made bigger, and when it disappears, the scoreboard would be made smaller again.

Thank you in advance.

**Comment by CatCoderr** [comment]
Sounds good. I'll implement it in spare time. Thank you for the suggestion.
