### ISSUE TITLE
1.20.6 packet changes makes kick occur

### ISSUE THREAD

**Issue by LukaDeVrij** [CatCoderr/ProtocolSidebar#74]
1.20.6 has changed some packets probably. Kick message mentions the packet set_experience.

Internal Exception: io.netty.handler.codec.DecoderException: Java.io.IOException: Packet play/clientbound/minecraft:set_experience (afr) was larger than I expected, found 63 bytes extra whilst reading packet clientbound/minecraft:set_experience

On experimental paper 1.20.6 build 36

(Issue similar to 1.20.4 issues from a couple months back)

**Comment by CatCoderr** [comment]
Will implement support of this version later. Thanks for feedback.

**Comment by TheFox580** [comment]
Same issue for 1.21
Paper 1.21-107
223 extra bytes
