### ISSUE TITLE
Snapshot repo down?

### ISSUE THREAD

**Issue by DasLixou** [CatCoderr/ProtocolSidebar#81]
Is the snapshot repo down?

**Comment by DxsSucuk** [comment]
Hey!
Maybe this PR might help you https://github.com/CatCoderr/ProtocolSidebar/pull/83?

**Comment by CatCoderr** [comment]
Repository now back online. Thanks for reporting!

**Comment by 114514ns** [comment]
> Repository now back online. Thanks for reporting!

It's down again
can you fix it?
